#include <iostream>
using namespace std;

int main()
{
	int i, j;

	i = 10; j = 20;
  if (i > 0) {

  }

  if (j > 0) {

  }

 // if (i > 0 && j > 0) {

 // }


  if (j > 0) {
    if (j > 0) {

    }
  }

  



  // i > 0 - TRUE
  if (i > 0) {
       // j > 0 - TRUE
       if(j>0) {

       } 
       // j > 0 - FALSE
       else {

       }
  }  
  else { // i > 0 - FALSE
    if(j>0) { // j > 0 - TRUE

    } 
    // j > 0 - FALSE
    else {

     }

    }

	// Nesed if 



	// if - else if


	


  
}


- Make the program that checks the increasing order
    Input : 5 integers( will be generated by rand() function)
    Output : True or False (Text string )

- Make a program that provides factors for a given number within a range
    Input: 1 integer within a given range
    Output: List of factors for the given number (ex. 12 has factors of 2*2*3)
    12 : 1, 2, 3, 4, 6, 12

- Make a program that gives the summation of odd numbers in a given range.
    Input : 2 integers for the range.
    Output : The sum of the numbers within the range.

- Make a program that gives the even numbers of a given range
    Input: 2 integers for the range
    Output: All of the even numbers within the range

- Make a program that gives factorial of any number entered.
    input: 1 integer 
    output: factorial of that number. ex: input 5, output = 5*4*3*2*1 put = 5*4*3*2*1