
/*- Make the program that checks the increasing order
    Input : 5 integers( will be generated by rand() function)
    Output : True or False (Text string )

- Make a program that provides factors for a given number within a range
    Input: 1 integer within a given range
    Output: List of factors for the given number (ex. 12 has factors of 2*2*3)
    12 : 1, 2, 3, 4, 6, 12

- Make a program that gives the summation of odd numbers in a given range.
    Input : 2 integers for the range.
    Output : The sum of the numbers within the range.

- Make a program that gives the even numbers of a given range
    Input: 2 integers for the range
    Output: All of the even numbers within the range

- Make a program that gives factorial of any number entered.
    input: 1 integer 
    output: factorial of that number. ex: input 5, output = 5*4*3*2*1 put = 5*4*3*2*1*/

 //- Make a program that convert a binary number to decimal number 
    //input: the binary number 
    //output: the decimal number 
#include <iostream>
#include <math.h>
using namespace std;
 
int main()
{
  long binaryNumber, remainder,decimalNumber,j;
  decimalNumber = 0; 
  j = 1;

	cout << " Please, enter a binary number: " << endl;
	cin >> binaryNumber;

  while (binaryNumber != 0) {
    remainder = binaryNumber % 10;
    decimalNumber = decimalNumber + remainder * j;
    j = j * 2;
    binaryNumber = binaryNumber / 10;
  }
  cout<<" The decimal number: " << decimalNumber << endl;
} 
